index:
  javascript:
    - lib/jquery.min.js
    - lib/jquery.percentageloader-0.2.js
    - model/action.js
    - helper/action.js
    - helper/js.js
    - home/manager.js
    - home/main.js
  stylesheet:
    - home/main.css

login:
  javascript:
    - lib/jquery.min.js
    - lib/jquery.percentageloader-0.2.js
    - model/action.js
    - helper/action.js
    - helper/js.js
    - home/login/manager.js
    - home/login/main.js
  stylesheet:
    - home/login/main.css